feat(ci): assemble job now does check for sub-site dependencies
!11

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -27,17 +27,17 @@ include:
       # - .gitlab-ci_common.yaml # 2
       # - template/automagic.gitlab-ci.yaml # 2
 
-Lint Markdown:
+Website.Lint:
     extends: .Lint_Markdown
 
 
-Main Site:
+Website.Build:
   extends: .MKDocs_Build
-  needs: [ 'Lint Markdown' ]
+  needs: [ 'Website.Lint' ]
   resource_group: preperation
 
 
-Assemble Site:
+Assemble.Website.Prepare:
 #  extends: .MKDocs_Build
   stage: prepare
 #  image: python:3.7.5-buster
@@ -50,31 +50,57 @@ Assemble Site:
     - echo "copy sub-repo source to (merge)" "$CI_PROJECT_DIR/artifacts/$CI_JOB_STAGE/$CI_JOB_NAME/source"
     - echo "mkdocs build source dir"
 #    - mkdir -p "$CI_PROJECT_DIR/artifacts/$CI_JOB_STAGE/$CI_JOB_NAME/full-site"
-    - mv "$CI_PROJECT_DIR/artifacts/build/Main Site/build" "$CI_PROJECT_DIR/artifacts/$CI_JOB_STAGE/$CI_JOB_NAME/"
+    - mv "$CI_PROJECT_DIR/artifacts/build/Website.Build/build" "$CI_PROJECT_DIR/artifacts/$CI_JOB_STAGE/$CI_JOB_NAME/"
     #- ls -laR $CI_PROJECT_DIR
     # remove ops placeholder index.html
     
 
     - echo "[DEBUG] fetch operations docs"
-    - 'curl --location --output operations-artifacts.zip --header "PRIVATE-TOKEN: ${GIT_COMMIT_TOKEN}" "https://gitlab.com/api/v4/projects/32419575/jobs/artifacts/development/download?job=Documentation%2EBuild"'
-    - unzip operations-artifacts.zip
-    - rm -Rf "$CI_PROJECT_DIR/artifacts/$CI_JOB_STAGE/$CI_JOB_NAME/build/operations/index.html"
-    - cp -rvf "$CI_PROJECT_DIR/artifacts/build/Website.Build/build/operations" "$CI_PROJECT_DIR/artifacts/$CI_JOB_STAGE/$CI_JOB_NAME/build/"
-    - rm -Rf "$CI_PROJECT_DIR/artifacts/build/Website.Build"
+    - 'HTTP_STATUS_FILE=$(curl --location -o /dev/null --silent --head --write-out "%{http_code}" --header "PRIVATE-TOKEN: ${GIT_COMMIT_TOKEN}" "https://gitlab.com/api/v4/projects/32419575/jobs/artifacts/development/download?job=Documentation%2EBuild")'
+    - echo "[DEBUG] HTTP_STATUS_FILE=$HTTP_STATUS_FILE"
+    - |
+      if [ "0$HTTP_STATUS_FILE" != "0200" ]; then 
+        echo "[ERROR] Unable to fetch Job Artifacts due to HTTP status of $HTTP_STATUS_FILE"; 
+        # exit 1; 
+      else
+        curl --location --output operations-artifacts.zip --header "PRIVATE-TOKEN: ${GIT_COMMIT_TOKEN}" "https://gitlab.com/api/v4/projects/32419575/jobs/artifacts/development/download?job=Documentation%2EBuild";
+        unzip operations-artifacts.zip;
+        rm -Rf "$CI_PROJECT_DIR/artifacts/$CI_JOB_STAGE/$CI_JOB_NAME/build/operations/index.html";
+        cp -rvf "$CI_PROJECT_DIR/artifacts/build/Documentation.Build/build/operations" "$CI_PROJECT_DIR/artifacts/$CI_JOB_STAGE/$CI_JOB_NAME/build/";
+        rm -Rf "$CI_PROJECT_DIR/artifacts/build/Documentation.Build";
+      fi
+
 
     - echo "[DEBUG] fetch gitlab-ci project docs"
-    - 'curl --location --output gitlab-ci-artifacts.zip --header "PRIVATE-TOKEN: ${GIT_COMMIT_TOKEN}" "https://gitlab.com/api/v4/projects/28543717/jobs/artifacts/development/download?job=Documentation%2EBuild"'
-    - unzip gitlab-ci-artifacts.zip
-    - rm -Rf "$CI_PROJECT_DIR/artifacts/$CI_JOB_STAGE/$CI_JOB_NAME/build/projects/gitlab-ci"
-    - cp -rvf "$CI_PROJECT_DIR/artifacts/build/Website.Build/build/projects/gitlab-ci" "$CI_PROJECT_DIR/artifacts/$CI_JOB_STAGE/$CI_JOB_NAME/build/projects/gitlab-ci/"
-    - rm -Rf "$CI_PROJECT_DIR/artifacts/build/Website.Build"
+    - 'HTTP_STATUS_FILE=$(curl --location -o /dev/null --silent --head --write-out "%{http_code}" --header "PRIVATE-TOKEN: ${GIT_COMMIT_TOKEN}" "https://gitlab.com/api/v4/projects/28543717/jobs/artifacts/development/download?job=Documentation%2EBuild")'
+    - echo "[DEBUG] HTTP_STATUS_FILE=$HTTP_STATUS_FILE"
+    - |
+      if [ "0$HTTP_STATUS_FILE" != "0200" ]; then 
+        echo "[ERROR] Unable to fetch Job Artifacts due to HTTP status of $HTTP_STATUS_FILE"; 
+        # exit 1; 
+      else
+        curl --location --output gitlab-ci-artifacts.zip --header "PRIVATE-TOKEN: ${GIT_COMMIT_TOKEN}" "https://gitlab.com/api/v4/projects/28543717/jobs/artifacts/development/download?job=Documentation%2EBuild";
+        unzip gitlab-ci-artifacts.zip;
+        rm -Rf "$CI_PROJECT_DIR/artifacts/$CI_JOB_STAGE/$CI_JOB_NAME/build/projects/gitlab-ci";
+        cp -rvf "$CI_PROJECT_DIR/artifacts/build/Documentation.Build/build/projects/gitlab-ci" "$CI_PROJECT_DIR/artifacts/$CI_JOB_STAGE/$CI_JOB_NAME/build/projects/gitlab-ci/";
+        rm -Rf "$CI_PROJECT_DIR/artifacts/build/Documentation.Build";
+      fi
+
 
     - echo "[DEBUG] fetch docker-mail project docs"
-    - 'curl --location --output docker-mail-artifacts.zip --header "PRIVATE-TOKEN: ${GIT_COMMIT_TOKEN}" "https://gitlab.com/api/v4/projects/33611657/jobs/artifacts/development/download?job=Documentation%2EBuild"'
-    - unzip docker-mail-artifacts.zip
-    - rm -Rf "$CI_PROJECT_DIR/artifacts/$CI_JOB_STAGE/$CI_JOB_NAME/build/projects/docker-mail"
-    - cp -rvf "$CI_PROJECT_DIR/artifacts/build/Website.Build/build/projects/docker-mail" "$CI_PROJECT_DIR/artifacts/$CI_JOB_STAGE/$CI_JOB_NAME/build/projects/docker-mail/"
-    - rm -Rf "$CI_PROJECT_DIR/artifacts/build/Website.Build"
+    - 'HTTP_STATUS_FILE=$(curl --location -o /dev/null --silent --head --write-out "%{http_code}" --header "PRIVATE-TOKEN: ${GIT_COMMIT_TOKEN}" "https://gitlab.com/api/v4/projects/33611657/jobs/artifacts/development/download?job=Documentation%2EBuild")'
+    - echo "[DEBUG] HTTP_STATUS_FILE=$HTTP_STATUS_FILE"
+    - |
+      if [ "0$HTTP_STATUS_FILE" != "0200" ]; then 
+        echo "[ERROR] Unable to fetch Job Artifacts due to HTTP status of $HTTP_STATUS_FILE"; 
+        # exit 1; 
+      else
+        curl --location --output docker-mail-artifacts.zip --header "PRIVATE-TOKEN: ${GIT_COMMIT_TOKEN}" "https://gitlab.com/api/v4/projects/33611657/jobs/artifacts/development/download?job=Documentation%2EBuild";
+        unzip docker-mail-artifacts.zip;
+        rm -Rf "$CI_PROJECT_DIR/artifacts/$CI_JOB_STAGE/$CI_JOB_NAME/build/projects/docker-mail";
+        cp -rvf "$CI_PROJECT_DIR/artifacts/build/Documentation.Build/build/projects/docker-mail" "$CI_PROJECT_DIR/artifacts/$CI_JOB_STAGE/$CI_JOB_NAME/build/projects/docker-mail/";
+        rm -Rf "$CI_PROJECT_DIR/artifacts/build/Documentation.Build";
+      fi
 
 
     # # below 2 lines commented out as need to ffigure out how to download artifacts.
@@ -93,7 +119,7 @@ Assemble Site:
     - echo "copy each sub-repo build to fullsite (merge)"
 #    - echo mv "$CI_PROJECT_DIR/artifacts/$CI_JOB_STAGE/$CI_JOB_NAME/full-site" public
   needs: 
-    - 'Main Site'
+    - 'Website.Build'
     # only available in gitlab premium
     # use: - "curl -O --header 'PRIVATE-TOKEN: ${GITLAB_API_TOKEN}' https://gitlab.example.com/api/v4/projects/${PROJECT_A_ID}/jobs/${REMOTE_JOB_ID}/artifacts/${REMOTE_FILENAME}"
     # - project: nofusscomputing/ops
@@ -117,8 +143,8 @@ pages:
   variables:
     GIT_STRATEGY: none
   script:
-    - mv "$CI_PROJECT_DIR/artifacts/prepare/Assemble Site/build" public
-  needs: [ 'Assemble Site' ]
+    - mv "$CI_PROJECT_DIR/artifacts/prepare/Assemble.Website.Prepare/build" public
+  needs: [ 'Assemble.Website.Prepare' ]
   environment: 
     name: staging
     url: $CI_PAGES_URL
@@ -160,10 +186,10 @@ pages:
 
 Unit Tests:
   extends: .Pytest_template
-  needs: [ 'Main Site' ]
+  needs: [ 'Website.Build' ]
   resource_group: preperation
   script:
-    - mv "$CI_PROJECT_DIR/artifacts/build/Main Site/build" build
+    - mv "$CI_PROJECT_DIR/artifacts/build/Website.Build/build" build
     - pytest --verbose --junitxml=unit_test.junit.xml --tb=line test/unit
     - cp *.junit.xml "$CI_PROJECT_DIR/artifacts/$CI_JOB_STAGE/$CI_JOB_NAME/"
     - echo "[DEBUG] python_exit[$python_exit]"
@@ -206,8 +232,8 @@ public_website:
     - echo Debug ANSIBLE_USER[$ANSIBLE_USER]
     - apt update
     - apt install --no-install-recommends -y ssh
-    - ls -la "$CI_PROJECT_DIR/artifacts/prepare/Assemble Site/build"
-    - mv "$CI_PROJECT_DIR/artifacts/prepare/Assemble Site/build" "$CI_PROJECT_DIR/public"
+    - ls -la "$CI_PROJECT_DIR/artifacts/prepare/Assemble.Website.Prepare/build"
+    - mv "$CI_PROJECT_DIR/artifacts/prepare/Assemble.Website.Prepare/build" "$CI_PROJECT_DIR/public"
     - rm -Rf "$CI_PROJECT_DIR/public/build"
     - ls -la "$CI_PROJECT_DIR"
     - ls -la "$CI_PROJECT_DIR/public"
@@ -215,7 +241,7 @@ public_website:
   script:
     - ssh ${ANSIBLE_USER}@${HOST_PUBLIC_WEBSITE} sudo rm -Rf ${PUBLIC_WEBSITE_PATH}/*
     - scp -r public/* ${ANSIBLE_USER}@${HOST_PUBLIC_WEBSITE}:${PUBLIC_WEBSITE_PATH}
-  needs: [ 'Assemble Site', 'Unit Tests']
+  needs: [ 'Assemble.Website.Prepare', 'Unit Tests']
   resource_group: production
   environment: 
     name: production
